source 'https://github.com/CocoaPods/Specs.git'

target 'LIGRippleView', :exclusive => true do
  pod "LIGRippleView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "LIGRippleView", :path => "../"

  
end
